name: pytorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.10.15=ha4d7672_0
  - cairo=1.14.12=h276e583_5
  - certifi=2018.10.15=py37_1000
  - cycler=0.10.0=py_1
  - dbus=1.13.0=h3a4f0e9_0
  - expat=2.2.5=hfc679d8_2
  - ffmpeg=4.0.2=ha0c5888_2
  - fontconfig=2.13.1=h65d0f4c_0
  - freeglut=3.0.0=hfc679d8_5
  - gettext=0.19.8.1=h5e8e0c9_1
  - glib=2.56.2=h464dc38_0
  - gmp=6.1.2=hfc679d8_0
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.12=hfc679d8_1
  - gst-plugins-base=1.12.5=hde13a9d_0
  - gstreamer=1.12.5=h5856ed1_0
  - harfbuzz=1.9.0=h04dbb29_1
  - hdf5=1.10.2=hc401514_2
  - icu=58.2=hfc679d8_0
  - jpeg=9c=h470a237_1
  - kiwisolver=1.0.1=py37h2d50403_2
  - libgfortran=3.0.0=1
  - libglu=9.0.0=0
  - libiconv=1.15=h470a237_3
  - libuuid=2.32.1=h470a237_2
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - matplotlib=3.0.0=py37h0b34cb6_1
  - nettle=3.3=0
  - openh264=1.8.0=hd28b015_0
  - openssl=1.0.2p=h470a237_1
  - pcre=8.41=hfc679d8_3
  - pixman=0.34.0=h470a237_3
  - pthread-stubs=0.4=h470a237_1
  - pyparsing=2.2.2=py_0
  - pyqt=5.6.0=py37h8210e8a_7
  - python-dateutil=2.7.3=py_0
  - qt=5.6.2=hf70d934_9
  - sip=4.18.1=py37hfc679d8_0
  - tornado=5.1.1=py37h470a237_0
  - x264=1!152.20180717=h470a237_1
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libice=1.0.9=h470a237_4
  - xorg-libsm=1.2.3=h8c8a85c_0
  - xorg-libx11=1.6.6=h470a237_0
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h470a237_7
  - blas=1.0=mkl
  - cffi=1.11.5=py37he75722e_1
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.0=118
  - jasper=2.0.14=h07fcdf6_1
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopencv=3.4.2=hb342d67_1
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py37h7dd41cf_0
  - mkl_random=1.0.1=py37h4414c95_1
  - ncurses=6.1=hf484d3e_0
  - ninja=1.8.2=py37h6bb024c_1
  - numpy=1.15.2=py37h1d66e8a_1
  - numpy-base=1.15.2=py37h81de0dd_1
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - pillow=5.3.0=py37h34e0f95_0
  - pip=10.0.1=py37_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycparser=2.19=py37_0
  - python=3.7.0=h6e4f718_3
  - readline=7.0=h7b6447c_5
  - setuptools=40.4.3=py37_0
  - six=1.11.0=py37_1
  - sqlite=3.25.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.32.1=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
  - pytorch=0.4.1=py37_py36_py35_py27__9.0.176_7.1.2_2
  - torchvision=0.2.1=py37_1
  - pip:
    - torch==0.4.1.post2
prefix: /home/ophiuchus/miniconda3/envs/pytorch

